image: node:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn test:unit

build:
  stage: build
  dependencies:
    - test
  script:
    - yarn build
  artifacts:
    paths:
      - dist

pages: # задание должно быть именованными страницами
  stage: deploy
  dependencies:
    - build
  script:
    - mv public public-vue # GitLab Pages хук для каталога public
    - mv dist public # переименование каталога dist (результат команды npm run build)
    - cp public/index.html public/404.html
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public # путь к артефакту должен быть /public для GitLab Pages
  only:
    - master
