image: node:latest

stages:
  - test
  - build
  - deploy

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - yarn install

test:
  stage: test
  script:
    - yarn test:unit

build:
  stage: build
  script:
    - yarn build

pages: # задание должно быть именованными страницами
  stage: deploy
  script:
    - mv public public-vue # GitLab Pages хук для каталога public
    - mv dist public # переименование каталога dist (результат команды npm run build)
    - cp public/index.html public/404.html
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public # путь к артефакту должен быть /public для GitLab Pages
  only:
    - master
